name: Deploy Astro site to GitHub Pages
on:
  push:
    branches: [main]      # adjust if your primary branch differs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install, build, and upload
        uses: withastro/action@v4      # upgrade from v2
        with:
          node-version: 22            # or 18 to match local
          # path: .                   # uncomment if Astro lives in a sub-folder
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4